### ISSUE TITLE
=>FileNotFoundError: [Errno 2] No such file or directory: '/home/heyuehui/Mal/backend/blueprints/task/utils/mc2/display/static/images/tempimagesb7198813-a6f6-4069-9c72-e980eaf44cd0.png'

### ISSUE THREAD

**Issue by dagrons** [dagrons/Mal_backend#2]
172.28.128.1 - - [26/Mar/2021 16:16:39] "POST /tasks/create HTTP/1.1" 200 -
Exception in thread Thread-7:
Traceback (most recent call last):
  File "/opt/python3.6.5/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/home/heyuehui/Mal/backend/blueprints/task/__init__.py", line 46, in run
    super().run()
  File "/opt/python3.6.5/lib/python3.6/threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "/home/heyuehui/Mal/backend/blueprints/task/__init__.py", line 68, in analyze
    local_analyze(task, res['local'])
  File "/home/heyuehui/Mal/backend/blueprints/task/__init__.py", line 109, in local_analyze
    type_res = model_analyze(type_path, type)
  File "/home/heyuehui/Mal/backend/blueprints/task/utils/analysis.py", line 30, in analyze
    "prob": predict_file(filepath, file_type),
  File "/home/heyuehui/Mal/backend/blueprints/task/utils/mc2/display/predict.py", line 116, in predict_file
    image = Image.open(path)
  File "/home/heyuehui/envs/mal/lib/python3.6/site-packages/PIL/Image.py", line 2652, in open
    fp = builtins.open(filename, "rb")
FileNotFoundError: [Errno 2] No such file or directory: '/home/heyuehui/Mal/backend/blueprints/task/utils/mc2/display/static/images/tempimages67532316-17f9-4fd6-87be-1fb8e603b992.png'

172.28.128.1 - - [26/Mar/2021 16:16:41] "GET /feature/show/67532316-17f9-4fd6-87be-1fb8e603b992 HTTP/1.1" 200 -
[2021-03-26 16:16:42,399] ERROR in app: Exception on /feature/report/get/67532316-17f9-4fd6-87be-1fb8e603b992 [GET]
Traceback (most recent call last):
  File "/home/heyuehui/envs/mal/lib/python3.6/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/heyuehui/envs/mal/lib/python3.6/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/heyuehui/envs/mal/lib/python3.6/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/heyuehui/envs/mal/lib/python3.6/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/heyuehui/envs/mal/lib/python3.6/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/heyuehui/envs/mal/lib/python3.6/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/heyuehui/Mal/backend/blueprints/feature/__init__.py", line 45, in get_report
    with open(type_res_path) as f:
FileNotFoundError: [Errno 2] No such file or directory: '/home/heyuehui/Mal/backend/storage/67532316-17f9-4fd6-87be-1fb8e603b992/png_res.json'
172.28.128.1 - - [26/Mar/2021 16:16:42] "GET /feature/report/get/67532316-17f9-4fd6-87be-1fb8e603b992 HTTP/1.1" 500 -

**Comment by dagrons** [comment]
bytes文件首先生成，如果bytes生成失败，造成线程中断，则可能造成png文件没生成
