### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory: '/home/heyuehui/Mal/backend/storage/781e4a5a-4ad9-436a-aeff-66e7babc7011/781e4a5a-4ad9-436a-aeff-66e7babc7011.bytes'

### ISSUE THREAD

**Issue by dagrons** [dagrons/Mal_backend#4]
VirusShare_729dae62ed542a25dfe81095897af430

**Comment by dagrons** [comment]
ndisasm: unable to open `/home/heyuehui/Mal/backend/storage/3d564ffa-282d-414b-a318-19b40d0a6214/3d564ffa-282d-414b-a318-19b40d0a6214.bytes': No such file or directory
Exception in thread Thread-12:
Traceback (most recent call last):
  File "/opt/python3.6.5/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/home/heyuehui/Mal/backend/blueprints/task/__init__.py", line 46, in run
    super().run()
  File "/opt/python3.6.5/lib/python3.6/threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "/home/heyuehui/Mal/backend/blueprints/task/__init__.py", line 68, in analyze
    local_analyze(task, res['local'])
  File "/home/heyuehui/Mal/backend/blueprints/task/__init__.py", line 109, in local_analyze
    type_res = model_analyze(type_path, type)
  File "/home/heyuehui/Mal/backend/blueprints/task/utils/analysis.py", line 30, in analyze
    "prob": predict_file(filepath, file_type),
  File "/home/heyuehui/Mal/backend/blueprints/task/utils/mc2/display/predict.py", line 112, in predict_file
    vec = readFromFile(file)
  File "/home/heyuehui/Mal/backend/blueprints/task/utils/mc2/bytes/create_data/create_image.py", line 45, in readFromFile
    with open(filename,encoding='ISO-8859-1') as file_object:
FileNotFoundError: [Errno 2] No such file or directory: '/home/heyuehui/Mal/backend/storage/3d564ffa-282d-414b-a318-19b40d0a6214/3d564ffa-282d-414b-a318-19b40d0a6214.bytes'

**Comment by dagrons** [comment]
原因是有的文件没有.text段
